### ISSUE TITLE
US15 - Immersive experience (wireframes)

### ISSUE THREAD

**Issue by Jottiana** [WildCodeSchool-2024-09/JS-Reims-p2-Mixology-Bar#13]
**As a user,**
**I want the site to be visually engaging,**
**So that I have a positive and immersive experience.**

Acceptance Criteria:

- [x] Criteria 1: The wireframe design follows a dark, neon theme with appropriate colors and styling.
- [x] Criteria 2: Visual and structural consistency across all pages through layout design.
- [x] Criteria 3: Wireframes for all pages (desktop and mobile).

Definition of Done:

- [x] All acceptance criteria are met.
- [ ] Code is reviewed and approved.
- [ ] Documentation is updated, if applicable.
- [x] Feature is deployed to the staging environment.

**Comment by paulcnl** [comment]
fini !!!!!!!!!!!!!!!!!!!!!!!!!!!
